### ISSUE TITLE
Difficulty to retrieve typing status of opponent in private dialog.

### ISSUE THREAD

**Issue by anismansuri** [QuickBlox/q-municate-services-ios#313] opened 2017-05-23 04:23 UTC
**Environment details**
*iOS version, Quickblox iOS SDK version, QMServices version*
'QuickBlox', '~> 2.9'
'QMServices', '~> 0.4'

**Did this work before?**
No

**Expected behavior**
In private dialog both user can see typing status of one another.
After sending image.

**Actual behavior**

        After sending image from user 1 to user 2. User 1 can't see the status of user 2 typing.
        And if user 1 goes to chatlist and come back user 2 dialog then it start working again.

**Steps to reproduce the behavior**
send image to user 2 from user 1.
and start typing in user 2.
User 1 will not be able to detect if user is typing.

**Comment by ghost** [comment] 2017-05-23 09:29
Closed as a duplicate of [#810](https://github.com/QuickBlox/quickblox-ios-sdk/issues/810)

**Closed as completed by ghost** 2017-05-23 09:29 UTC
